require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3007 }

  # MAIL_DELIVERY picks how mail leaves a development server:
  #   smtp (default)  real mail through the Gmail SMTP settings in application.rb
  #                   (the owner's own dev testing, unchanged)
  #   test            nothing leaves the box (QA/dev servers: invites, sign-up
  #                   confirmations and Resend go to *.test addresses)
  #   letter_opener   opens each mail locally, only if that gem is installed
  # Anything else stops the boot, so a typo never silently sends real mail.
  mail_delivery = ENV.fetch("MAIL_DELIVERY", "smtp")
  allowed = %w[smtp test]
  allowed << "letter_opener" if Gem.loaded_specs.key?("letter_opener")
  unless allowed.include?(mail_delivery)
    raise ArgumentError, "MAIL_DELIVERY=#{mail_delivery.inspect} is not one of #{allowed.join(', ')}"
  end
  config.action_mailer.delivery_method = mail_delivery.to_sym

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Separate cable process — mobile connects here directly.
  config.action_cable.mount_path = nil
  config.action_cable.url = ENV.fetch("ACTION_CABLE_URL", "ws://localhost:3098/hatiwal-cable")
  config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # CI — Android emulator host authorization.
  # The emulator reaches the host machine via 10.0.2.2 and sends
  # "Host: 10.0.2.2:3000" on every request. Rails 8's
  # ActionDispatch::HostAuthorization rejects any host not on the allowlist
  # (default: localhost variants only), returning 403 Blocked Host and breaking
  # all Maestro E2E flows. Allow 10.0.2.2 and localhost only in CI so local
  # development is unaffected.
  if ENV["CI"].present?
    config.hosts << "10.0.2.2"
    config.hosts << "localhost"
  end
end
